name: Main Branch Tests

on:
  push:
    branches: [main]

jobs:
  lint-unit-e2e-full:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.54.1-jammy

    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      # コンテナ内のプリインストール済みブラウザを使用し、ダウンロードを抑止
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      HOME: /root

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      # Next.jsビルドキャッシュ
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - run: npm run type-check
      - run: npm run lint
      - run: npm test

      - run: npm run build
      - run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
